### ISSUE TITLE
NPE: Attempt to invoke virtual method 'io.smooch.core.c.ac io.smooch.core.c.w.e()'

### ISSUE THREAD

**Issue by matejhacin** [zendesk/sunshine-conversations-android#113]
This crash keeps appearing in my logs every once in a while. It seems to occur very rarely (less than 0.1% of the users and even then not in every session).

> java.lang.NullPointerException: Attempt to invoke virtual method 'io.smooch.core.c.ac io.smooch.core.c.w.e()' on a null object reference
    at io.smooch.core.service.SmoochService.a
    at io.smooch.core.service.SmoochService.a
    at io.smooch.core.service.SmoochService$10$1.a
    at io.smooch.core.service.SmoochService$10$1.a
    at io.smooch.core.b.f$13.a
    at io.smooch.core.b.a.b$1$2.run
    at android.os.Handler.handleCallback(Handler.java:790)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6494)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

It happened in an earlier version of Smooch Android SDK first, so I thought that updating the gradle dependency will fix it, but it did not. I am now using version 5.9.0 for a while and it still seems to happen.

I just noticed there's a newer version (5.9.1) available, but there's no mention of this crash in change log, so I assume it will still happen.

This is how I init Smooch inside my Application class:

` Smooch.init(this, new Settings(AppConstants.SMOOCH_APP_ID), null);`

**Comment by channguyen** [comment]
Seeing this quite a bit from Fabric as well.

**Comment by wmora** [comment]
Thanks! It's hard to deduce the bug from the stacktrace, unfortunately. I'll keep the issue open to keep track of it, please share any additional info that you find!

**Comment by channguyen** [comment]
It happens a lot on our app now, almost 1%.

**Comment by karolzdebel** [comment]
Also experiencing this

**Comment by channguyen** [comment]
There are so many crashes like this on our app. Can you guys do something about it? The code is obfuscated and we don't know exactly how the trace look like. Could you guys use the mapping.txt to see what's going on. Currently this is the highest crash rate in our app and it keep increasing day by day!

**Comment by wmora** [comment]
@channguyen what SDK version are you on?

**Comment by DataWearsAHood** [comment]
Hello!

Looks like a few nullpointer crashes have been fixed since this issue was first reported (v5.15.0 v7.0.2).
Please reopen this issue if you are still experiencing this crash with the latest release.
