### ISSUE TITLE
Take Photo not working

### ISSUE THREAD

**Issue by parthanjaria** [zendesk/sunshine-conversations-android#126]
This repository's issues are reserved for bug reports only.

 **I'm submitting a ...**
  - [x] bug report

 **What is the current behavior?**
Open the Smooch Ui chat, click on camera icon in the bottom left corner.
dialog appears to select "Take Photo"/"Use last photo taken"/Choose from Library"
When click on "Take photo" a toast appears "There was a problem launching the camera".

 **What is the expected behavior?**
Camera should open

 **Please tell us about your environment:**
- SDK version : 5.4.0
- OS version : 7.1.1

**Comment by wmora** [comment]
Is this happening on all your devices or a specific device? Also, do you see any error message in the logs?

**Comment by ppilip** [comment]
This happens to me also. Message in the log is:

> There was a problem accessing the file. Please ensure your FileProviderAuthorities have been correctly set.

Can you give a quick working example of defining one in Manifest.xml and which exactly string is to be set in the

`setFileProviderAuthorities(String fileProviderAuthorities)` of the `Settings` object ?

I've tried some combinations, but I still get the same error.

**Comment by adamszewe** [comment]
Hi, this issue still exists in the latest version, `6.2.0` and was also present in previous versions.
Choosing `Take a Quick Photo` option the first time asks for permissions, as it's supposed to do, but clicking it again afterwards does nothing.

On the other hand the `Choose from Photo Gallery` option when chosen the first time asks for access to storage, and when chosen the second time it allows to load the images properly from gallery.

I tested on the following devices:
* LG G7 ThinQ - Android: 8.0.0
* Huawei Y5 (2018) - Android: 8.1.0
* (Huawei) Honor 8 Pro - Android: 9.0.0

The `Take a Quick Photo` does not work on any of the above devices while `Choose from Photo Gallery` works flawlessly.

**Comment by adamszewe** [comment]
Turns out Smooch sdk is not to blame, but in our case it was Hockeyapp that was adding a `maxSdkVersion` to the permission in its manifest that is later merged with the app's one.

Thus `WRITE_EXTERNAL_STORAGE` that is used by Smooch is always denied because this is what we get in the merged manifest:
![image](https://user-images.githubusercontent.com/6529875/61496612-076ce180-a9bd-11e9-86b7-7f6471bef316.png)

The solution is as easy as: 
```
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="replace" />

```
