### ISSUE TITLE
Can not take photo and choose photo from library on Android 10

### ISSUE THREAD

**Issue by cuk2dn95** [zendesk/sunshine-conversations-android#143]
This repository's issues are reserved for bug reports only.

 **I'm submitting a ...**
  - [x] bug report

 **Please provide the steps to reproduce and, if possible, a minimal demo of the problem**. Ideally a sample project
Open the Smooch Ui chat, click on the plus icon in the bottom left corner.
a dialog appears to select "Take a Quick Photo/Choose from Photo Library"

Case 1: 
Choose **Take a Quick Photo** action
result: the operation failed 
error message: 

> There was a problem launching the camera

screen:
 ![Screen Shot 2020-04-08 at 09 30 14](https://user-images.githubusercontent.com/22941292/78738246-95d62880-797b-11ea-9c00-1d5e54116ff0.png)
log: 
`-E/ConversationFragment: There was a problem saving the file.
-io.smooch.ui.ConversationActivity} has no registered input channel`

Case 2: 
Choose **Choose from Photo Library** -> Pick a image
result: the operation failed
error message: 

> There was a problem retrieving your photo

screen:
![Screen Shot 2020-04-08 at 09 20 53](https://user-images.githubusercontent.com/22941292/78738385-f5343880-797b-11ea-977d-8801ac41c848.png)
log: `E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /storage/emulated/0/DCIM/Camera/IMG_20200407_152819.jpg: open failed: EACCES (Permission denied)`

 **What is the expected behavior?**
Case 1: the camera should open and take photo successfully
Case 2: pick a picture and send successfully

 **Please tell us about your environment:**
- SDK version: 7.0.1
- OS version: 10 

 **Other information** 
The app does not restrict any permission:
![Screen Shot 2020-04-07 at 15 58 32](https://user-images.githubusercontent.com/22941292/78738703-b9e63980-797c-11ea-81ae-b2bda7e86032.png)

**Comment by rubnov** [comment]
Is there a fix for this issue yet? Could you provide an update? 
We are paying Sunshine / Zendesk customer and this issue is causing us real pain.

**Comment by wmora** [comment]
Thanks for reporting. This issue has been filed internally for the team to review and prioritize

**Comment by rubnov** [comment]
This issue has been raised a month ago. Do you have any update or an estimate on when you expect to fix this? 

This is causing us a lot of pain. We rely on attachments / screenshots being submitted by users via the mobile app. We need a solution fast. If this isn’t something that’s going to be fixed in a week or two please let us know so we can find alternative solutions.

**Comment by luca-dall** [comment]
Any news on this issue? we have seen the same in our app

**Comment by DataWearsAHood** [comment]
Hello all,

Looks like there's a linked [internal] PR that's since been merged and [released in v7.0.2](https://github.com/zendesk/sunshine-conversations-android/releases/tag/7.0.2)!
