### ISSUE TITLE
With Anonymous user:  Can't logout or delete smooch user data

### ISSUE THREAD

**Issue by khoatd92** [zendesk/sunshine-conversations-android#146]
**I'm submitting a ...**
  - [x] bug report

 **What is the current behavior?**
My application sign-in by anonymous login provided by Smooch
Try to send some chat message then logout or delete smooch user data and re-login on the same device
Chat data still there

 **What is the expected behavior?**
- All data should be deleted whenever user logout or delete account 

 **Please tell us about your environment:**
- SDK version: 7.0.2
- OS version: Android 10

**Comment by DataWearsAHood** [comment]
Hello Khoa,

Unfortunately, if the user is not logged-in, it is not possible to log-out.
There are a few [options for managing message history, documented here](https://docs.smooch.io/guide/clearing-conversations/)
