### ISSUE TITLE
Smooch SDK slowing down build time due to support library usage

### ISSUE THREAD

**Issue by prfarlow1** [zendesk/sunshine-conversations-android#147]
The Smooch SDK, both Smooch Core and Smooch UI, depend on the Android Support Library, which has been deprecated for over 2 years. Using the Smooch SDK in our app means we have to use the [Android jetifier tool](https://developer.android.com/studio/command-line/jetifier), which [makes build times slower](https://adambennett.dev/2020/08/disabling-jetifier/). It also means the Smooch SDK is depending on libraries that no longer receive updates or bug fixes.

Can I get a timeline on when the Smooch Android SDK will be migrated from the support library to AndroidX?

**Comment by DataWearsAHood** [comment]
Hi Peter,

The team tells me that v8.0.0 has in fact been migrated to AndroidX!
