### ISSUE TITLE
io.smooch:ui:8.0.0 still needs Jetifier

### ISSUE THREAD

**Issue by jshvarts** [zendesk/sunshine-conversations-android#148]
Hello,

io.smooch:ui:8.0.0 is supposed to be using AndroidX dependencies only but [CanIDropJetifier](https://github.com/plnice/can-i-drop-jetifier) is reporting that it is not:
```
./gradlew -Pandroid.enableJetifier=false canIDropJetifier
Cannot drop Jetifier due to following external dependencies:

* io.smooch:ui:8.0.0
  \-- com.davemorrissey.labs:subsampling-scale-image-view:3.10.0
   \-- com.android.support:exifinterface:27.1.0
  \-- com.davemorrissey.labs:subsampling-scale-image-view:3.10.0
   \-- com.android.support:support-annotations:27.1.0
```

**Comment by DataWearsAHood** [comment]
Hi @jshvarts ,

Thanks for bringing this one to our attention - it's been added to our dev queue!
Keep an eye on our releases to know when this has been addressed.
