### ISSUE TITLE
Top of screen is extra white space 

### ISSUE THREAD

**Issue by billnbell** [zendesk/sunshine-conversations-android#151]
**I'm submitting a ...**
  - [ X  bug report

 **What is the current behavior?**

There is a large white space at the top of the Android Conversation screen.

![C3EADBE2-E236-419A-9C76-1BB84F7913E2](https://user-images.githubusercontent.com/25377089/106878970-cf5cea80-6697-11eb-9f49-395f6fe0d2a9.jpeg)

 **What is the expected behavior?**

See picture - should not have white space at top of conversation.

 **Please tell us about your environment:**
- SDK version - 8.1.0 and 8.0.0
- OS version
PIxel 3A

**Comment by DataWearsAHood** [comment]
Hi @billnbell,

Thanks for bringing this one to our attention - it's been added to our bug queue!
Keep an eye on our releases to know when this has been addressed.
