### ISSUE TITLE
JCenter is shutting down

### ISSUE THREAD

**Issue by prfarlow1** [zendesk/sunshine-conversations-android#152]
The setup guide for the Android SDK indicates that this library is published on JCenter. JCenter is shutting down in 3 months. After that time, any client projects will no longer be able to pull down this library as a dependency. The authors of this library should move to publishing to a different publish repository like Maven Central.

Announcement: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by DataWearsAHood** [comment]
Hi @prfarlow1 

Thanks for bringing this one to our attention - it's been added to our dev queue!
Keep an eye on our releases to know when this has been addressed.

**Comment by JesusM** [comment]
Bumping this as as far as I know, artifacts are still on jcenter. I'd be nice to start moving them to maven central, as jcenter is meant to stop serving artifacts in less than a year and a lot of teams are going to start planning their migrations soon 😉 .
