### ISSUE TITLE
How to get more from Conversation - older messages?

### ISSUE THREAD

**Issue by billnbell** [zendesk/sunshine-conversations-android#153]
In IOS I can scroll back to get more messages. In Android how do I get more messages on scroll ? It is not working for me.

I cannot find a way to do this.

How many messages come back by default? 100? How do I get More messages?

**Comment by wmora** [comment]
Hi there! Pagination support for older messages is not available on Android. This has already been filed as a feature request to our Product team. 100 messages are loaded for the conversation.

**Comment by Vitor-Bukovitz** [comment]
hey @wmora, sometimes it loads less than 20 for me. I'm not sure why this is happening it simply doesn't load further if you don't send any messages that after a certain time. Meanwhile, on iOS, it works perfectly. Is there some kind of limitation for date storage for Android or something like that? Thanks!

**Comment by DataWearsAHood** [comment]
@Vitor-Bukovitz 
If you pull the conversation record via API, have >20 messages but only 20 messages loaded in to the WebSDK (without any delegates, as these can modify messages that get displayed), please reach out to our advocacy team for further support.
