### ISSUE TITLE
Feature: Smooch.isLogin()

### ISSUE THREAD

**Issue by billnbell** [zendesk/sunshine-conversations-android#154]
Can we consider adding Smooch.isLogin() to check to see if the user is logged in.

**Comment by DataWearsAHood** [comment]
Hello @billnbell,
I've shared your feedback with the Product team.
In the meantime, you can read the `externalId` user parameter; for anonymous users, you should have `user.externalId: null`

**Comment by billnbell** [comment]
For V7.1.2 there is no externalId. Can we use userId instead?

**Comment by DataWearsAHood** [comment]
Yes, identifiers moved around a bit in v8 to align with the v2 REST APIs:
< [android-]v8: appUserId + userId
[android-]v8 +: userId + externalId
