### ISSUE TITLE
Solve the problem of Android Studio 4.2

### ISSUE THREAD

**Issue by hussainriab** [zendesk/sunshine-conversations-android#156]
Android resource compilation failed
E:\Therosaryofthebeliever2\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-w٣٦٠dp-port-v13\values-w٣٦٠dp-port-v13.xml: AAPT: error: invalid configuration 'w٣٦٠dp-port-v13'.

**Comment by DataWearsAHood** [comment]
Hello @hussainriab,

Are you able to reproduce the issue with the included /demo app?
Does more than one device demonstrate the same behaviour?
