### ISSUE TITLE
Can't update firebase-bom, migrating to FCM's token APIs required

### ISSUE THREAD

**Issue by Fraid** [zendesk/sunshine-conversations-android#157]
Hi team,

Are you planning to update to the latest version of firebase-messaging or is there an ETA for that?

Because updating firebase-bom to 28.2.0, will made app crash do to missing FirebaseInstanceID class.
 
```
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId;
        at io.smooch.core.service.SmoochService.a()
        at io.smooch.core.service.SmoochService.I()
        at io.smooch.core.service.SmoochService$h.a()
        at io.smooch.core.service.SmoochService$h.a()
        at io.smooch.core.k.g.onResponse()
```

From Firebase team
https://firebase.google.com/support/release-notes/android#messaging_v22-0-0

> Caution: This is a breaking change for apps that use FCM and the deprecated Firebase Instance ID API to manage registration tokens.
> We strongly recommend migrating to FCM's token APIs. If you're unable to migrate to the replacement APIs, add a direct dependency on the firebase-iid library to your build.gradle file.

**Comment by DataWearsAHood** [comment]
Hello @Fraid 

While we are planning to make this upgrade, there is a backend infra dependency which must be resolved first, so no ETA for this update, unfortunately.
Keep an eye on future release notes to know once this has been released. (internal ref: MFD-3676)
