### ISSUE TITLE
 Duplicate class a.a.a.a found

### ISSUE THREAD

**Issue by visttux** [zendesk/sunshine-conversations-android#158]
Hi, I'm having the following issue trying to add the dependency to our project (io.smooch:core 8.2.1):

> java.lang.RuntimeException: Duplicate class a.a.a.a found in modules core-8.2.1-runtime.jar (io.smooch:core:8.2.1) and jetified-android-sdk-1.3.8-runtime.jar (com.riskified:android-sdk:1.3.8)

Seems that there is a clash for the name obfuscated "a.a.a.a" with the one used by another library. 

you can add the flag `flattenpackagehierarchy` in proguard rules to move the obfuscated classes to a unique package and almost avoid any chance of collision with other libraries

**Comment by DataWearsAHood** [comment]
Hi @visttux 

Thanks for pointing this out and sharing the solution!
