### ISSUE TITLE
Crash by java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by visttux** [zendesk/sunshine-conversations-android#171]
**I'm submitting a ...**
  - [X] bug report

 **What is the current behavior?**
App crashes with a ConcurrentModificationException after a network call

 **What is the expected behavior?**
App shouldn't crash

 **Please tell us about your environment:**
- SDK version: 9.0.2

**Stack trace**

> java.util.LinkedHashMap$LinkedHashIterator.nextNode (LinkedHashMap.java:757)
> java.util.LinkedHashMap$LinkedKeyIterator.next (LinkedHashMap.java:780)
> java.util.AbstractCollection.addAll (AbstractCollection.java:343)
> java.util.TreeSet.addAll (TreeSet.java:312)
> io.smooch.core.facade.g.a (g.java:24)
> io.smooch.core.facade.h.a (h.java:2)
> io.smooch.core.service.b.a (b.java:37)
> io.smooch.core.service.SmoochService$f0.a (SmoochService.java:73)
> io.smooch.core.service.SmoochService$f0.a (SmoochService.java:2)
> io.smooch.core.network.g.onResponse (g.java:52)
> retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0 (DefaultCallAdapterFactory.java:89)
> retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.$r8$lambda$hVGjmafRi6VitDIrPNdoFizVAdk (DefaultCallAdapterFactory.java)
> retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$$InternalSyntheticLambda$0$daf5173ad73a9dc0e8131143f299c222e2ca4cddd7cb10b2d0a6e331a0602ae1$0.run (DefaultCallAdapterFactory.java:6)

 **Suggested solutions**
- Create a copy of the Collection to perform modifications
- Use a thread-safe API (e.g Collections.newSetFromMap(new ConcurrentHashMap<>()) or ConcurrentHashMap.newKeySet())

**Comment by DataWearsAHood** [comment]
@visttux Is this crash still present with the [latest release](https://github.com/zendesk/sunshine-conversations-android/releases/tag/9.1.1)?

**Comment by visttux** [comment]
fixed
