### ISSUE TITLE
Crash on MessageListAdapter

### ISSUE THREAD

**Issue by visttux** [zendesk/sunshine-conversations-android#174]
**I'm submitting a ...**
  - [X] bug report
  
 **What is the current behavior?**
App crashes

**What is the expected behavior?**
App shouldn't crash

 **Please tell us about your environment:**
- SDK Version: 9.0.4

**Stack trace**

> Fatal Exception: java.lang.NullPointerException
> Attempt to invoke virtual method 'void android.widget.TextView.setVisibility(int)' on a null object reference
> io.smooch.ui.adapter.MessageListAdapter$i.a (MessageListAdapter.java:58)
> io.smooch.ui.adapter.MessageListAdapter$i.a (MessageListAdapter.java)
> io.smooch.ui.adapter.MessageListAdapter.onBindViewHolder (MessageListAdapter.java:8)

**Comment by xukai59740** [comment]
<img width="388" alt="截屏2022-07-26 下午4 08 33" src="https://user-images.githubusercontent.com/15320822/180956581-234ee092-b108-42d8-a551-92189ec00ea9.png">
My app also has this crash, It affects many devices and users.

**Comment by Ramzi-Alqrainy** [comment]
We are facing the same issue with our application in production. Please we need your action to solve it.

**Comment by whath** [comment]
hey,May I ask if we have fixed this in 9.1.0?

**Comment by MettSc** [comment]
Hello, I am also getting this crash. Is there any progress on this one?

**Comment by Gabogg07** [comment]
Hello, do we have any updates on this crash?
When or why does it happens? I am facing this issue as well

**Comment by zsoltboldizsar** [comment]
Although clear reference to this issue is not mentioned in the release notes of 9.1.1 (https://github.com/zendesk/sunshine-conversations-android/releases/tag/9.1.1) we thought we'd try to update regardless and it seems like the crash is not being reproduced anymore 🎉 

Would be awesome to hear confirmation from maintainers, but until then thanks to developers!

**Comment by serabile** [comment]
Hello, has anyone had a problem with INTEGRATION_ID after updating from 9.0.1 to 9.1.1 ?
I'm getting an error while initializing smooch with the same integration_id as before
`Smooch init  Callback: Response{status=404, error='Smooch integration id was invalid.', data=INVALID_ID}`
@zsoltboldizsar  you had this ?
@wmora you have an idea ? did we change something?
Thanks

**Comment by visttux** [comment]
fixed
