### ISSUE TITLE
Changelog for latest release 9.3.0

### ISSUE THREAD

**Issue by upendrap** [zendesk/sunshine-conversations-android#186]
Hi Team 👋 
The latest releases are missing changelog.
https://github.com/zendesk/sunshine-conversations-android/releases/tag/ui%2F9.3.0
https://github.com/zendesk/sunshine-conversations-android/releases/tag/core%2F9.3.0

Can you please share the changelog?

**Comment by upendrap** [comment]
Gentle reminder 🙏

**Comment by upendrap** [comment]
Gentle reminder 🙏

**Comment by mathroule** [comment]
Hi

The changelog has been added to https://github.com/zendesk/sunshine-conversations-android/releases/tag/core%2F9.3.0 and https://github.com/zendesk/sunshine-conversations-android/releases/tag/ui%2F9.3.0.

**Comment by upendrap** [comment]
Thank you @mathroule 👍
