### ISSUE TITLE
Notification Action Intent Override not working when application is launched from notification tap in quit state

### ISSUE THREAD

**Issue by dgrover-spotnana** [zendesk/sunshine-conversations-android#188]
**For support questions, please visit [our help page](https://smooch.io/help/)**.

This repository's issues are reserved for bug reports only.

 **I'm submitting a ...**
  - [x] bug report
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

 **What is the current behavior?**

When the application is either in foreground or background, the [Notification Action Intent Override](https://docs.smooch.io/guide/native-android-sdk/#notification-action-intent-override) for `Smooch_settings_notificationIntent` works just fine. But when the application is in quit state and the user receives a notification, on tapping the notification the override doesn't seem to work as it still launches the `ConversationActivity`

 **Please provide the steps to reproduce and, if possible, a minimal demo of the problem**. Ideally a sample project

Replace

`<string name="Smooch_settings_notificationIntent">io.smooch.ui.ConversationActivity</string>`

with

`<string name="Smooch_settings_notificationIntent">com.yourApp.MainActivity</string>`

 **What is the expected behavior?**

The override should work even when notification is tapped in quit state i.e. `ConversationActivity` should not be opened directly

 **Please tell us about your environment:**
- SDK version

```
io.smooch:core:9.2.0
io.smooch:ui:9.2.0
```
- OS version

```
API Level 34 (Android 14)
```

**Comment by dgrover-spotnana** [comment]
Can someone provide an update on this ?

**Comment by IanArb** [comment]
Please submit bug reports to [Zendesk](https://support.zendesk.com/hc/en-us/articles/4408843597850) and be sure to consult our [Getting help section](https://developer.zendesk.com/documentation/zendesk-web-widget-sdks/getting_support_on_zendesk_mobile_sdks/) of our documentation.
